# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Tobias van der Werff
author:
    name: Tobias van der Werff
    email:
# Write an awesome description for your new site here. You can edit this
# line in _config.yml. It will appear in your document head meta (for
# Google search results) and in your feed.xml site description.
description: Personal website of Tobias van der Werff
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tobiasvanderwerff.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: tobiasnvdw
github_username: tobiasvanderwerff

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Page links to show in the top right of the header
header_pages:
  - blog.md
  - tags.md

comments:
  giscus:
    enabled: true
    repo: "tobiasvanderwerff/tobiasvanderwerff.github.io"
    repo_id: "R_kgDOLtxmig"
    category: "Announcements"
    category_id: "DIC_kwDOLtxmis4Cf6JU"
    mapping: "og:title"
    reactions_enabled: "1"
    theme: "light"
